# Generated by Django 5.2 on 2025-04-28 00:58

import common_app.validators
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name of the client (2-100 characters).', max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='First name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(100, message='First name cannot exceed 100 characters.'), common_app.validators.validate_name], verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter the last name of the client (2-100 characters).', max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Last name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(100, message='Last name cannot exceed 100 characters.'), common_app.validators.validate_name], verbose_name='Last Name')),
                ('email', models.EmailField(error_messages={'unique': 'A client with this email address already exists.'}, help_text='Enter a unique email address for the client.', max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Enter the client's phone number (Max 25 characters). Accepts various international formats.", max_length=25, null=True, region=None, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, help_text="Enter the client's home address.", null=True, verbose_name='Address')),
                ('emergency_contact_name', models.CharField(blank=True, help_text="Enter the name of the client's emergency contact (optional).", max_length=100, null=True, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Enter the phone number of the client's emergency contact (optional). Accepts various international formats.", max_length=25, null=True, region=None, verbose_name='Emergency Contact Phone Number')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this client profile is considered active. Unselect this instead of deleting profiles to archive.', verbose_name='Active Status')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark as deleted instead of actually deleting the record.', verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
