# Generated by Django 5.2 on 2025-04-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this client profile is considered active. Unselect this instead of deleting profiles to archive.', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text="Enter the phone number of the client's emergency contact.", max_length=25, null=True, verbose_name='Emergency Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Enter the client's phone number (Max 20 characters).", max_length=25, null=True, verbose_name='Phone Number'),
        ),
    ]
