# Generated by Django 5.2 on 2025-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0002_client_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
