# Generated by Django 5.2 on 2025-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0003_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
