# Generated by Django 5.2 on 2025-04-24 04:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A client with this email address already exists.'}, help_text='Enter a unique email address for the client.', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text="Enter the name of the client's emergency contact (optional).", max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Enter the phone number of the client's emergency contact (optional). Accepts various international formats.", max_length=25, null=True, region=None, verbose_name='Emergency Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Enter the client's phone number (Max 25 characters). Accepts various international formats.", max_length=25, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
