# Generated by Django 5.2 on 2025-04-24 22:22

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_app', '0005_alter_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(max_length=255, verbose_name='Street Address Line 1')),
                ('street_address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State / Province / Region')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal/ZIP Code')),
                ('country', django_countries.fields.CountryField(max_length=100, verbose_name='Country')),
                ('address_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAILING', 'Mailing'), ('BILLING', 'Billing'), ('OTHER', 'Other')], default='PHYSICAL', help_text='Type of address (Physical, Mailing, Billing)', max_length=50, verbose_name='Address Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['client', 'address_type'],
            },
        ),
    ]
