# Generated by Django 5.2 on 2025-04-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('WAITLIST', 'Waitlist'), ('PROSPECTIVE', 'Prospective')], default='PROSPECTIVE', help_text='Select the current status of the dog within the system.', max_length=20, verbose_name='Status'),
        ),
    ]
