# Generated by Django 5.2 on 2025-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0002_alter_dog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the dog.', null=True, upload_to='dog_photos/', verbose_name='Photo'),
        ),
    ]
