# Generated by Django 5.2 on 2025-04-24 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0003_remove_dog_photo_path_dog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='veterinarian_phone',
            field=models.CharField(blank=True, help_text="Please enter the phone number of the dog's primary veterinarian/clinic.", max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Veterinarian Phone Number'),
        ),
    ]
